package com.test.agendagroup

rule "agendagroup test 1"
agenda-group "test"
when
    eval(true)
then
    System.out.println("agendagroup test 1 执行完毕!");
end

rule "agendagroup test 2"
agenda-group "test"
when
    eval(true)
then
    System.out.println("agendagroup test 2 执行完毕!");
end

rule "agendagroup test 3"
agenda-group "test3"
when
    eval(true)
then
    System.out.println("agendagroup test 3 执行完毕!");
end